name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: Environments
        run: npm run build:env
        env:
          PRODUCTION: ${{ secrets.PRODUCTION }}
          API_URL: ${{ secrets.API_URL }}
          USERS_URL: ${{ secrets.USERS_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          MATCHES_URL: ${{ secrets.MATCHES_URL }}
          DELETE_URL: ${{ secrets.DELETE_URL }}
          CREATE_URL: ${{ secrets.CREATE_URL }}

      - name: 🧪 Testing
        run: npm test
        env:
          PRODUCTION: ${{ secrets.PRODUCTION }}
          API_URL: ${{ secrets.API_URL }}
          USERS_URL: ${{ secrets.USERS_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          MATCHES_URL: ${{ secrets.MATCHES_URL }}
          DELETE_URL: ${{ secrets.DELETE_URL }}
          CREATE_URL: ${{ secrets.CREATE_URL }}
