name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: Environments
        run: "npx ng  generate environments && sed -i 's|};|\\n production: '$PRODUCTION',\\n apiUrl: '$API_URL',\\n path: {\\n users: '$USERS_URL',\\n loginUser: '$LOGIN_URL',\\n matches: '$MATCHES_URL'\\n }\\n};|' ./src/environments/environment.ts"
        env:
          PRODUCTION: ${{ secrets.PRODUCTION }}
          API_URL: ${{ secrets.API_URL }}
          USERS_URL: ${{ secrets.USERS_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          MATCHES_URL: ${{ secrets.MATCHES_URL }}

      - name: 🧪 Testing
        run: npm test
        env:
          PRODUCTION: ${{ secrets.PRODUCTION }}
          API_URL: ${{ secrets.API_URL }}
          USERS_URL: ${{ secrets.USERS_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          MATCHES_URL: ${{ secrets.MATCHES_URL }}
